substitutions:
  device_name: tzspserial
  friendly_name: TZSP Serial
  esp_board: esp32-poe-iso

external_components:
  - source: github://Omniflux/esphome-tzsp
  - source: github://Omniflux/esphome-tzspserial

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  platformio_options:
    build_flags:
      - -std=gnu++2a
    build_unflags:
      - -std=gnu++11

esp32:
  board: ${esp_board}
  framework:
    type: esp-idf

api:

logger:
  level: DEBUG

ota:
  - platform: esphome
    password: !secret ota_password

sensor:
  - platform: uptime
    name: Uptime

button:
  - platform: restart
    name: Restart
  - platform: safe_mode
    name: Restart (Safe Mode)

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  power_pin: GPIO12

uart:
  tx_pin: GPIO13
  rx_pin: GPIO14
  baud_rate: 500
  parity: EVEN

tzsp_serial:
  frame_size: 8
  inverted: true
  tzsp:
    ip: 192.168.1.10
#    port: 37008
    protocol: 255